"""Adding log tables

Revision ID: 391732c2010e
Revises: 9dad7b603b4b
Create Date: 2024-08-16 15:07:45.555888

"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '391732c2010e'
down_revision: Union[str, None] = '9dad7b603b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'request_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('query_params', sa.JSON(), nullable=True),
        sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('confirmed_piece_of_shit', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'update_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('number_of_flats', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_log')
    op.drop_table('request_log')
    # ### end Alembic commands ###
