"""Refactor providers

Revision ID: d32761407362
Revises: 391732c2010e
Create Date: 2025-06-01 22:39:00.155259

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd32761407362'
down_revision: Union[str, None] = '391732c2010e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the existing index first
    op.drop_index('ix_flat_ff_id', table_name='flat')
    
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('flat', schema=None) as batch_op:
        # Rename ff_id to provider_message_id and change type from int to string
        batch_op.alter_column('ff_id',
                              new_column_name='provider_message_id',
                              type_=sa.String(),
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('original_text',
                              new_column_name='raw_text',
                              existing_type=sa.String())
    
    # Add new columns
    op.add_column('update_log', sa.Column(
        'data_provider',
        sa.String(),
        nullable=False,
        server_default='flip_flat'
    ))
    op.add_column('update_log', sa.Column(
        'city',
        sa.String(),
        nullable=False,
        server_default='Tbilisi'
    ))
    op.add_column('flat', sa.Column(
        'data_provider',
        sa.String(),
        nullable=False,
        server_default='flip_flat'
    ))
    op.add_column('flat', sa.Column(
        'city',
        sa.String(),
        nullable=False,
        server_default='Tbilisi'
    ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_log', 'data_provider')

    # Handle non-convertible string values before changing type back to integer
    connection = op.get_bind()
    connection.execute(sa.text("""
                               UPDATE flat
                               SET provider_message_id = '-1'
                               WHERE provider_message_id !~ '^-?[0-9]+$' OR provider_message_id = ''
                               """))
    
    with op.batch_alter_table('flat', schema=None) as batch_op:
        # Revert raw_text back to original_text
        batch_op.alter_column('raw_text', 
                              new_column_name='original_text',
                              existing_type=sa.String())

        # Revert provider_message_id back to ff_id with integer type
        batch_op.alter_column('provider_message_id',
                              new_column_name='ff_id',
                              type_=sa.Integer(),
                              existing_type=sa.String(),
                              nullable=False)
    
    op.create_index('ix_flat_ff_id', 'flat', ['ff_id'], unique=True)
    op.drop_column('flat', 'data_provider')
    op.drop_column('flat', 'city')
    op.drop_column('update_log', 'city')
    # ### end Alembic commands ###